export const theme = {
	colors: {
		primary: 'var(--colors-primary)',
		secondary: 'var(--colors-secondary)',
		warning: 'var(--colors-warning)',
		error: 'var(--colors-error)',
		success: 'var(--colors-success)',
		border: 'var(--colors-border)',
		info: 'var(--colors-info)',
		background: {
			tooltip: 'var(--colors-background-tooltip)',
			paper: 'var(--colors-background-paper)',
			element: 'var(--colors-background-element)',
			elementHover: 'var(--colors-background-elementHover)',
			sidebar: 'var(--colors-background-sidebar)',
		},
		foreground: {
			primary: 'var(--colors-foreground-primary)',
			secondary: 'var(--colors-foreground-secondary)',
		},
		text: {
			primary: 'var(--colors-text-primary)',
			secondary: 'var(--colors-text-secondary)',
			disabled: 'var(--colors-text-disabled)',
			hint: 'var(--colors-text-hint)',
		},
	},
	spacing: {
		'1': 'var(--spacing-1)',
		'2': 'var(--spacing-2)',
		'3': 'var(--spacing-3)',
		'4': 'var(--spacing-4)',
		'5': 'var(--spacing-5)',
		'6': 'var(--spacing-6)',
		'7': 'var(--spacing-7)',
		'8': 'var(--spacing-8)',
		'9': 'var(--spacing-9)',
		'10': 'var(--spacing-10)',
		'12': 'var(--spacing-12)',
		'16': 'var(--spacing-16)',
		'20': 'var(--spacing-20)',
	},
	shadow: {
		'1': 'var(--shadow-1)',
		'2': 'var(--shadow-2)',
		'3': 'var(--shadow-3)',
		'4': 'var(--shadow-4)',
		'5': 'var(--shadow-5)',
	},
	elevation: {
		'1': 'var(--elevation-1)',
		'2': 'var(--elevation-2)',
		'3': 'var(--elevation-3)',
		'4': 'var(--elevation-4)',
		'6': 'var(--elevation-5)',
	},
	fontSize: {
		xs: 'var(--fontSize-xs)',
		sm: 'var(--fontSize-sm)',
		base: 'var(--fontSize-base)',
		lg: 'var(--fontSize-lg)',
		xl: 'var(--fontSize-xl)',
		'2xl': 'var(--fontSize-2xl)',
		'3xl': 'var(--fontSize-3xl)',
		'4xl': 'var(--fontSize-4xl)',
	},
	fontWeight: {
		normal: 'var(--fontWeight-normal)',
		medium: 'var(--fontWeight-medium)',
		semibold: 'var(--fontWeight-semibold)',
		bold: 'var(--fontWeight-bold)',
	},
	lineHeight: {
		none: 'var(--lineHeight-none)',
		tight: 'var(--lineHeight-tight)',
		snug: 'var(--lineHeight-snug)',
		normal: 'var(--lineHeight-normal)',
		relaxed: 'var(--lineHeight-relaxed)',
		loose: 'var(--lineHeight-loose)',
	},
	radius: {
		small: 'var(--radius-small)',
		medium: 'var(--radius-medium)',
		large: 'var(--radius-large)',
	},
} as const;

export type Theme = typeof theme;
export type SpacingKey = keyof Theme['spacing'];
